// <auto-generated />
using System;
using LingoMQ.Infrastructure.Persistense.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lingomq.Persistense.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    partial class UsersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LingoMQ.Core.Domain.Users.AuthorizationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("auth_type");

                    b.Property<int?>("UserCredentialsId")
                        .HasColumnType("integer")
                        .HasColumnName("user_credentials_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("auth_value");

                    b.HasKey("Id")
                        .HasName("pk_authorization_type");

                    b.HasIndex("UserCredentialsId")
                        .HasDatabaseName("ix_authorization_type_user_credentials_id");

                    b.ToTable("authorization_type", (string)null);
                });

            modelBuilder.Entity("LingoMQ.Core.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CredentialsId")
                        .HasColumnType("integer")
                        .HasColumnName("credentials_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nickname");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("CredentialsId")
                        .HasDatabaseName("ix_users_credentials_id");

                    b.HasIndex("ImageId")
                        .HasDatabaseName("ix_users_image_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("LingoMQ.Core.Domain.Users.UserCredentials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_salt");

                    b.HasKey("Id")
                        .HasName("pk_user_credentials");

                    b.ToTable("user_credentials", (string)null);
                });

            modelBuilder.Entity("LingoMQ.Core.Domain.Users.UserImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("X")
                        .HasColumnType("integer")
                        .HasColumnName("x");

                    b.Property<int>("Y")
                        .HasColumnType("integer")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_user_images");

                    b.ToTable("user_images", (string)null);
                });

            modelBuilder.Entity("LingoMQ.Core.Domain.Words.WordInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Transcription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("transcription");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word");

                    b.HasKey("Id")
                        .HasName("pk_word_infos");

                    b.ToTable("word_infos", (string)null);
                });

            modelBuilder.Entity("WordInfoWordInfo", b =>
                {
                    b.Property<Guid>("TranslationsId")
                        .HasColumnType("uuid")
                        .HasColumnName("translations_id");

                    b.Property<Guid>("WordInfoId")
                        .HasColumnType("uuid")
                        .HasColumnName("word_info_id");

                    b.HasKey("TranslationsId", "WordInfoId")
                        .HasName("pk_word_info_word_info");

                    b.HasIndex("WordInfoId")
                        .HasDatabaseName("ix_word_info_word_info_word_info_id");

                    b.ToTable("word_info_word_info", (string)null);
                });

            modelBuilder.Entity("LingoMQ.Core.Domain.Users.AuthorizationType", b =>
                {
                    b.HasOne("LingoMQ.Core.Domain.Users.UserCredentials", null)
                        .WithMany("AuthorizationTypes")
                        .HasForeignKey("UserCredentialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_authorization_type_user_credentials_user_credentials_id");
                });

            modelBuilder.Entity("LingoMQ.Core.Domain.Users.User", b =>
                {
                    b.HasOne("LingoMQ.Core.Domain.Users.UserCredentials", "Credentials")
                        .WithMany()
                        .HasForeignKey("CredentialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_user_credentials_credentials_id");

                    b.HasOne("LingoMQ.Core.Domain.Users.UserImage", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .HasConstraintName("fk_users_user_images_image_id");

                    b.OwnsOne("LingoMQ.Core.Domain.Users.UserRole", "Role", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("role_name");

                            b1.Property<int>("Weight")
                                .HasColumnType("integer")
                                .HasColumnName("role_weight");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId")
                                .HasConstraintName("fk_users_users_id");
                        });

                    b.Navigation("Credentials");

                    b.Navigation("Image");

                    b.Navigation("Role")
                        .IsRequired();
                });

            modelBuilder.Entity("LingoMQ.Core.Domain.Words.WordInfo", b =>
                {
                    b.OwnsOne("LingoMQ.Core.Domain.Words.Language", "Language", b1 =>
                        {
                            b1.Property<Guid>("WordInfoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("language_code");

                            b1.Property<string>("SubCode")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("language_sub_code");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("language_value");

                            b1.HasKey("WordInfoId");

                            b1.ToTable("word_infos");

                            b1.WithOwner()
                                .HasForeignKey("WordInfoId")
                                .HasConstraintName("fk_word_infos_word_infos_id");
                        });

                    b.OwnsOne("LingoMQ.Core.Domain.Words.WordThematics", "Thematics", b1 =>
                        {
                            b1.Property<Guid>("WordInfoId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Category")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("thematics_category");

                            b1.HasKey("WordInfoId");

                            b1.ToTable("word_infos");

                            b1.WithOwner()
                                .HasForeignKey("WordInfoId")
                                .HasConstraintName("fk_word_infos_word_infos_id");
                        });

                    b.Navigation("Language")
                        .IsRequired();

                    b.Navigation("Thematics")
                        .IsRequired();
                });

            modelBuilder.Entity("WordInfoWordInfo", b =>
                {
                    b.HasOne("LingoMQ.Core.Domain.Words.WordInfo", null)
                        .WithMany()
                        .HasForeignKey("TranslationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_word_info_word_info_word_infos_translations_id");

                    b.HasOne("LingoMQ.Core.Domain.Words.WordInfo", null)
                        .WithMany()
                        .HasForeignKey("WordInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_word_info_word_info_word_infos_word_info_id");
                });

            modelBuilder.Entity("LingoMQ.Core.Domain.Users.UserCredentials", b =>
                {
                    b.Navigation("AuthorizationTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
